import { defineConfig } from "vite";
import react from "@vitejs/plugin-react-swc";
import path from "path";
import { VitePWA } from "vite-plugin-pwa";
import compression from 'vite-plugin-compression';

export default defineConfig({
  base: "/",
  plugins: [
    react(),
    compression({
      algorithm: 'brotliCompress',
      ext: '.br',
    }),
    VitePWA({
      registerType: "autoUpdate",
      includeAssets: ["favicon.ico", "logo-icon.svg", "cedarboost-logo.png", "assets/hub_gaming.png", "assets/hub_smm.png", "assets/hub_wallet.png", "assets/whish-logo.png"],
      manifest: {
        name: "Cedar Boost",
        short_name: "CedarBoost",
        description: "Premium digital recharge — SMM, games, wallet top-ups.",
        theme_color: "#D61414",
        background_color: "#050505",
        display: "standalone",
        orientation: "portrait",
        start_url: "/",
        scope: "/",
        lang: "en",
        categories: ["finance", "utilities"],
        shortcuts: [
          {
            name: "My Orders",
            short_name: "Orders",
            description: "Track your active orders",
            url: "/orders",
            icons: [{ src: "/logo-icon.svg", sizes: "any" }]
          },
          {
            name: "Wallet",
            short_name: "Wallet",
            description: "Check balance & top up",
            url: "/dashboard",
            icons: [{ src: "/logo-icon.svg", sizes: "any" }]
          },
          {
            name: "SMM Engine",
            short_name: "SMM",
            description: "Social media growth services",
            url: "/smm-engine",
            icons: [{ src: "/logo-icon.svg", sizes: "any" }]
          }
        ],
        icons: [
          // SVG — scales perfectly on all modern browsers
          {
            src: "/logo-icon.svg",
            sizes: "any",
            type: "image/svg+xml",
            purpose: "any"
          },
          // PNG fallbacks (generated by scripts/generate-icons.mjs)
          {
            src: "/icons/icon-72.png",
            sizes: "72x72",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-96.png",
            sizes: "96x96",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-128.png",
            sizes: "128x128",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-144.png",
            sizes: "144x144",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-152.png",
            sizes: "152x152",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-180.png",
            sizes: "180x180",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-192.png",
            sizes: "192x192",
            type: "image/png",
            purpose: "any"
          },
          {
            src: "/icons/icon-384.png",
            sizes: "384x384",
            type: "image/png",
            purpose: "any"
          },
          // 512 maskable — safe zone for Android adaptive icons
          {
            src: "/icons/icon-512.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "any maskable"
          }
        ]
      },
      workbox: {
        globPatterns: ["**/*.{js,css,html,ico,png,svg,woff2}"],
        runtimeCaching: [
          {
            urlPattern: /^https:\/\/.*\.supabase\.co\/.*/i,
            handler: "StaleWhileRevalidate",
            options: {
              cacheName: "supabase-data",
              expiration: {
                maxEntries: 200,
                maxAgeSeconds: 60 * 60 * 48 // 48 hours
              },
              cacheableResponse: {
                statuses: [0, 200]
              }
            }
          },
          {
            urlPattern: /^https:\/\/fonts\.(?:googleapis|gstatic)\.com\/.*/i,
            handler: "CacheFirst",
            options: {
              cacheName: "google-fonts",
              expiration: {
                maxEntries: 20,
                maxAgeSeconds: 60 * 60 * 24 * 365 // 1 year
              }
            }
          }
        ]
      }
    })
  ],
  build: {
    reportCompressedSize: true,
    chunkSizeWarningLimit: 1000,
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ['react', 'react-dom', 'react-router-dom', '@supabase/supabase-js'],
          ui: ['lucide-react', 'recharts', 'sonner']
        }
      }
    }
  },
  server: {
    host: "127.0.0.1",
    port: 8081,
    strictPort: true
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
